<?php

/*********************************************************************
* Extension configuration file for ext "svconnector_json".
*
* Generated by ext 02-05-2016 09:36 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Connector service - JSON',
  'description' => 'Connector service for JSON data',
  'category' => 'services',
  'version' => '2.0.0',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'clearcacheonload' => 0,
  'author' => 'Prakash A Bhat, Francois Suter (Cobweb)',
  'author_email' => 'typo3@cobweb.ch',
  'author_company' => '',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '7.6.0-7.99.99',
      'svconnector' => '3.0.0-0.0.0',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  '_md5_values_when_last_written' => 'a:17:{s:9:"ChangeLog";s:4:"b12d";s:11:"LICENSE.txt";s:4:"6404";s:10:"README.txt";s:4:"54b9";s:13:"composer.json";s:4:"fd02";s:21:"ext_conf_template.txt";s:4:"ef02";s:12:"ext_icon.png";s:4:"be69";s:17:"ext_localconf.php";s:4:"5ae1";s:33:"Classes/Service/ConnectorJson.php";s:4:"f399";s:26:"Documentation/Includes.txt";s:4:"c83c";s:23:"Documentation/Index.rst";s:4:"2cac";s:26:"Documentation/Settings.yml";s:4:"adf2";s:37:"Documentation/Configuration/Index.rst";s:4:"3183";s:33:"Documentation/Developer/Index.rst";s:4:"e414";s:36:"Documentation/Installation/Index.rst";s:4:"9247";s:36:"Documentation/Introduction/Index.rst";s:4:"1e78";s:40:"Resources/Private/Language/locallang.xlf";s:4:"5443";s:42:"Resources/Public/Samples/Configuration.txt";s:4:"0b0b";}',
  'comment' => 'Verified compatibility with TYPO3 CMS 7; moved to namespaces.',
  'user' => 'francois',
);

?>